[tagging]
system_message = "You are an expert in terms of understanding the sentiment of a text."
human_message = """Given this input {text}
can you tell me whether the overall sentiment of the text indicates some sort of confusion or is it positive or negative?
Example:
Ya, yes, ok, yep are all positive sentiments
no, na, ewww, nothing are negative sentiments
umm is confused
"""
